import type { DailyEvent, DailySnapshot, DailyTheme } from "@/lib/dailySnapshot";
import type { LowPositionWorkbench, MessageRow, ThemeRow } from "@/lib/lowPositionWorkbench";

export const SEED_DATE = "2026-05-14";

export type TopicCardSeed = {
  name: string;
  heat: number;
  change: string;
  description: string;
  tags: string[];
  icon: string;
};

export type SampleSeed = {
  title: string;
  kind: string;
  description: string;
  locked?: boolean;
};

export type CategorySeed = {
  title: string;
  tags: string[];
};

function candidate(name: string, code: string, score: number) {
  return {
    name,
    code,
    score,
    mappingReason: "公开信息客观映射，需继续核验主营、订单与公告证据。",
    sourceReason: "公开报道提及产业链关联。",
    sourceReasonSourceSite: "公开资讯",
    sourceReasonSourceUrl: "",
    sourceReasonTitle: "产业链更新",
    sourceReasonExcerpt: "相关环节被反复提及，适合进入研究池。",
    llmReason: "与主题链条存在客观关联，用于研究优先级排序。",
    scarcityNote: "需要继续核对订单、产能和公告证据。",
    judgeExplanation: "纳入观察池。",
    riskFlags: ["主题波动", "证据仍需交叉验证"],
  };
}

export const seedEvents: DailyEvent[] = [
  {
    key: "ev-robot-policy",
    eventId: "EV-001",
    title: "工信部：加快推动人形机器人创新发展，培育未来产业新赛道",
    eventType: "产业",
    eventSubject: "人形机器人",
    eventTime: "2026-05-14T09:48:00+08:00",
    impactDirection: "观察",
    impactScope: "产业链",
    summary: "政策强调形成安全可靠的产业体系，推动人形机器人在制造业、服务业和家庭场景的规模化应用。",
    themes: ["人形机器人", "AI 应用"],
    industries: ["机器人"],
    sourceRefs: ["公开政策"],
    sourceId: "policy",
    sourceName: "公开政策",
  },
  {
    key: "ev-ai-chip",
    eventId: "EV-002",
    title: "多家公司披露 AI 芯片与算力订单进展，国产替代线索继续强化",
    eventType: "公司",
    eventSubject: "AI 算力",
    eventTime: "2026-05-14T09:31:00+08:00",
    impactDirection: "观察",
    impactScope: "算力",
    summary: "企业披露显示算力相关订单和交付节奏仍在增长，适合继续跟踪业绩、利用率和供给约束。",
    themes: ["算力租赁", "AI 芯片", "国产替代"],
    industries: ["算力"],
    sourceRefs: ["公司公告"],
    sourceId: "company",
    sourceName: "公司公告",
  },
  {
    key: "ev-low-altitude",
    eventId: "EV-003",
    title: "发改委：支持低空经济基础设施建设，打造新增量场景",
    eventType: "政策",
    eventSubject: "低空经济",
    eventTime: "2026-05-14T09:12:00+08:00",
    impactDirection: "观察",
    impactScope: "基础设施",
    summary: "政策推动低空应用场景、基础设施和空域管理规则落地，产业链进入证据跟踪窗口。",
    themes: ["低空经济", "通用航空", "新基建"],
    industries: ["低空经济"],
    sourceRefs: ["公开政策"],
    sourceId: "policy",
    sourceName: "公开政策",
  },
  {
    key: "ev-pv-export",
    eventId: "EV-004",
    title: "光伏协会：1-4 月组件出口同比增长，新兴市场需求旺盛",
    eventType: "产业",
    eventSubject: "光伏设备",
    eventTime: "2026-05-14T08:55:00+08:00",
    impactDirection: "观察",
    impactScope: "新能源",
    summary: "海外需求与技术迭代共同支撑光伏设备线索，但价格和库存仍需持续核对。",
    themes: ["光伏设备", "新能源"],
    industries: ["光伏"],
    sourceRefs: ["行业协会"],
    sourceId: "media",
    sourceName: "行业协会",
  },
  {
    key: "ev-solid-battery",
    eventId: "EV-005",
    title: "动力电池企业：固态电池研发取得新进展，产业化节奏受关注",
    eventType: "公司",
    eventSubject: "固态电池",
    eventTime: "2026-05-14T08:41:00+08:00",
    impactDirection: "观察",
    impactScope: "动力电池",
    summary: "固态电池能量密度和小批量生产计划成为后续观察节点，需要区分技术进展与商业化确定性。",
    themes: ["固态电池", "动力电池", "储能"],
    industries: ["新能源"],
    sourceRefs: ["互动平台"],
    sourceId: "company",
    sourceName: "公司公告",
  },
  {
    key: "ev-macro-policy",
    eventId: "EV-006",
    title: "央行：将实施适度宽松的货币政策，加大逆周期调节力度",
    eventType: "宏观",
    eventSubject: "货币政策",
    eventTime: "2026-05-14T08:28:00+08:00",
    impactDirection: "观察",
    impactScope: "宏观流动性",
    summary: "流动性和政策节奏会影响主题扩散环境，但页面不输出涨跌预测或交易建议。",
    themes: ["宏观经济", "货币政策"],
    industries: ["宏观"],
    sourceRefs: ["公开发布会"],
    sourceId: "policy",
    sourceName: "公开政策",
  },
];

export const seedThemes: DailyTheme[] = [
  {
    key: "humanoid-robot",
    themeName: "人形机器人",
    clusterId: "theme-humanoid-robot",
    coreNarrative: "政策支持、产业订单和核心零部件迭代正在形成连续催化，适合放入观察池做证据链跟踪。",
    firstSeenTime: "2026-05-14T09:00:00+08:00",
    latestSeenTime: "2026-05-14T14:30:00+08:00",
    relatedEventsCount: 5,
    sourceCount: 3,
    heatScore: 98.7,
    catalystScore: 88.4,
    continuityScore: 83.2,
    fermentationScore: 92.1,
    lowPositionScore: 78.5,
    lowPositionReason: "事件密集但尚未形成一致交易拥挤，适合作为低位研究卡继续验证。",
    fermentationStage: "fermenting",
    riskNotice: "仅作公开信息研究观察，不构成投资建议。",
    genericRiskNotices: ["证据仍需持续补充，防止单一来源噪音。"],
    candidateStocks: [candidate("拓普集团", "601689", 76), candidate("鸣志电器", "603728", 71)],
    topEvidence: [{ title: "机器人产业政策催化", summary: "政策文件强调产业体系和场景应用。", eventTime: "2026-05-14T09:48:00+08:00" }],
    firstSourceUrl: "",
    topCandidatePurityScore: 76,
    researchPositioningNote: "优先核对政策、订单、零部件放量和历史相似案例。",
    referenceType: "政策+产业",
    futureWatchSignals: ["新增订单", "核心零部件量产", "政策细则"],
    riskFlags: ["单日热度波动", "主题拥挤"],
    similarCases: [{ runId: "demo-20260514", themeName: "机器人", referenceType: "历史主题扩散", similarityScore: 0.72, resultLabel: "可参考", historicalPathSummary: "政策催化后关注产业链验证。" }],
    latestCatalysts: [{ title: "机器人政策催化", summary: "多源报道显示产业政策持续强化。", eventTime: "2026-05-14T09:48:00+08:00" }],
  },
  {
    key: "low-altitude-economy",
    themeName: "低空经济",
    clusterId: "theme-low-altitude",
    coreNarrative: "基础设施、空管规则和应用场景同步推进，事件具有跨来源扩散特征。",
    firstSeenTime: "2026-05-14T08:40:00+08:00",
    latestSeenTime: "2026-05-14T13:10:00+08:00",
    relatedEventsCount: 4,
    sourceCount: 3,
    heatScore: 85.3,
    catalystScore: 81.2,
    continuityScore: 79.4,
    fermentationScore: 86.2,
    lowPositionScore: 70.8,
    lowPositionReason: "政策方向明确，但商业化节奏仍需验证。",
    fermentationStage: "spreading",
    riskNotice: "需要继续跟踪地方试点、招标和空域管理细则。",
    genericRiskNotices: ["政策落地节奏可能影响验证。"],
    candidateStocks: [candidate("中信海直", "000099", 69)],
    topEvidence: [{ title: "低空基础设施政策", summary: "政策强调拓展低空应用场景。", eventTime: "2026-05-14T09:12:00+08:00" }],
    firstSourceUrl: "",
    topCandidatePurityScore: 69,
    researchPositioningNote: "跟踪基础设施、运营牌照和地方试点。",
    referenceType: "政策",
    futureWatchSignals: ["地方试点", "基建招标", "空域管理细则"],
    riskFlags: ["政策预期差"],
    similarCases: [],
    latestCatalysts: [{ title: "低空基建政策", summary: "政策催化带来产业链观察窗口。", eventTime: "2026-05-14T09:12:00+08:00" }],
  },
  {
    key: "ai-compute-rental",
    themeName: "算力租赁",
    clusterId: "theme-ai-compute",
    coreNarrative: "AI 模型需求、国产芯片替代和数据中心扩容共同支撑算力服务主题。",
    firstSeenTime: "2026-05-14T08:30:00+08:00",
    latestSeenTime: "2026-05-14T11:20:00+08:00",
    relatedEventsCount: 3,
    sourceCount: 2,
    heatScore: 82.1,
    catalystScore: 76.4,
    continuityScore: 74.2,
    fermentationScore: 80.5,
    lowPositionScore: 64.2,
    lowPositionReason: "业绩与订单证据需要继续交叉验证。",
    fermentationStage: "watching",
    riskNotice: "需要区分业绩事实与市场想象空间。",
    genericRiskNotices: [],
    candidateStocks: [candidate("润建股份", "002929", 63)],
    topEvidence: [{ title: "AI 芯片需求保持高增长", summary: "企业披露显示算力相关需求仍在增长。", eventTime: "2026-05-14T09:31:00+08:00" }],
    firstSourceUrl: "",
    topCandidatePurityScore: 63,
    researchPositioningNote: "关注订单、利用率、折旧和现金流。",
    referenceType: "业绩+订单",
    futureWatchSignals: ["客户订单", "机柜利用率", "芯片供应"],
    riskFlags: ["估值波动"],
    similarCases: [],
    latestCatalysts: [{ title: "AI 算力业绩线索", summary: "业绩披露成为主题验证入口。", eventTime: "2026-05-14T09:31:00+08:00" }],
  },
  {
    key: "pv-equipment",
    themeName: "光伏设备",
    clusterId: "theme-pv-equipment",
    coreNarrative: "新技术迭代和海外需求共同支撑设备更新线索，库存与价格是主要风险。",
    firstSeenTime: "2026-05-14T08:55:00+08:00",
    latestSeenTime: "2026-05-14T10:15:00+08:00",
    relatedEventsCount: 2,
    sourceCount: 2,
    heatScore: 79.6,
    catalystScore: 73.5,
    continuityScore: 70.2,
    fermentationScore: 74.8,
    lowPositionScore: 58.6,
    lowPositionReason: "出口数据修复但价格链条仍需观察。",
    fermentationStage: "watching",
    riskNotice: "警惕价格波动和海外需求波动。",
    genericRiskNotices: [],
    candidateStocks: [],
    topEvidence: [{ title: "组件出口增长", summary: "行业协会数据显示新兴市场需求改善。", eventTime: "2026-05-14T08:55:00+08:00" }],
    firstSourceUrl: "",
    topCandidatePurityScore: null,
    researchPositioningNote: "跟踪出口、排产和设备订单。",
    referenceType: "产业数据",
    futureWatchSignals: ["出口订单", "新技术扩产", "库存变化"],
    riskFlags: ["价格波动"],
    similarCases: [],
    latestCatalysts: [{ title: "光伏出口线索", summary: "新兴市场需求成为验证点。", eventTime: "2026-05-14T08:55:00+08:00" }],
  },
  {
    key: "solid-state-battery",
    themeName: "固态电池",
    clusterId: "theme-solid-battery",
    coreNarrative: "能量密度突破和小批量生产计划提升关注度，产业化节奏仍需证据验证。",
    firstSeenTime: "2026-05-14T08:41:00+08:00",
    latestSeenTime: "2026-05-14T10:02:00+08:00",
    relatedEventsCount: 2,
    sourceCount: 2,
    heatScore: 72.4,
    catalystScore: 71.5,
    continuityScore: 66.1,
    fermentationScore: 70.3,
    lowPositionScore: 61.5,
    lowPositionReason: "技术推进明确，但商业化仍处早期验证。",
    fermentationStage: "watching",
    riskNotice: "技术和量产节奏存在不确定性。",
    genericRiskNotices: [],
    candidateStocks: [],
    topEvidence: [{ title: "固态电池研发进展", summary: "互动平台披露研发阶段性进展。", eventTime: "2026-05-14T08:41:00+08:00" }],
    firstSourceUrl: "",
    topCandidatePurityScore: null,
    researchPositioningNote: "跟踪材料体系、设备和试产节点。",
    referenceType: "技术进展",
    futureWatchSignals: ["试产节点", "材料验证", "客户测试"],
    riskFlags: ["产业化不确定"],
    similarCases: [],
    latestCatalysts: [{ title: "固态电池研发节点", summary: "技术突破线索进入观察池。", eventTime: "2026-05-14T08:41:00+08:00" }],
  },
];

export const topicCards: TopicCardSeed[] = [
  { name: "人形机器人", heat: 98.7, change: "+8.5%", description: "政策催化与产业突破并行，商业化落地加速。", tags: ["伺服系统", "减速器", "传感器"], icon: "robot" },
  { name: "低空经济", heat: 85.3, change: "+6.2%", description: "基建加速、场景拓展，产业链证据持续增加。", tags: ["eVTOL", "起降场", "空管系统"], icon: "plane" },
  { name: "算力租赁", heat: 82.1, change: "+4.1%", description: "AI 算力需求爆发，租赁模式持续受益。", tags: ["IDC", "GPU", "液冷散热"], icon: "cpu" },
  { name: "光伏设备", heat: 79.6, change: "+2.8%", description: "新技术迭代和海外需求共同支撑设备更新。", tags: ["TOPCon", "HJT", "组件设备"], icon: "activity" },
  { name: "固态电池", heat: 72.4, change: "+1.7%", description: "能量密度突破，产业化进程进入观察窗口。", tags: ["硫化物", "电解质", "锂金属"], icon: "battery" },
  { name: "AI 应用", heat: 70.8, change: "+1.2%", description: "大模型落地加速，应用生态持续丰富。", tags: ["办公工具", "智能体", "多模态"], icon: "cpu" },
];

export const categorySeeds: CategorySeed[] = [
  { title: "AI", tags: ["AI 应用", "算力租赁", "AI 芯片", "人形机器人", "工业机器人"] },
  { title: "新能源", tags: ["光伏设备", "储能", "固态电池", "动力电池", "风电设备"] },
  { title: "制造", tags: ["半导体设备", "半导体材料", "消费电子", "汽车产业链", "医疗器械"] },
  { title: "其他", tags: ["军工", "大消费", "高端制造", "国产替代", "新基建", "金融科技"] },
];

export const sampleSeeds: SampleSeed[] = [
  { kind: "复盘", title: "人形机器人产业链复盘", description: "梳理产业链演进、技术路线及核心公司表现。", locked: true },
  { kind: "复盘", title: "低空经济政策与产业链梳理", description: "跟踪地方试点、基础设施和运营牌照的证据链。", locked: true },
  { kind: "复盘", title: "光伏产业链周期分析", description: "观察技术迭代、海外需求和库存价格变化。", locked: true },
  { kind: "研究", title: "算力租赁订单与利用率跟踪", description: "核对订单、机柜利用率、折旧与现金流。", locked: true },
  { kind: "研究", title: "固态电池量产节点观察", description: "区分技术突破、试产节奏和商业化确定性。", locked: true },
  { kind: "研究", title: "AI 应用生态扩散路径", description: "跟踪模型能力、商业模式和用户付费验证。", locked: true },
];

const workbenchThemes: ThemeRow[] = seedThemes.slice(0, 4).map((theme, index) => ({
  theme_name: theme.themeName,
  low_position_score: theme.lowPositionScore,
  low_position_reason: theme.lowPositionReason,
  fermentation_phase: theme.fermentationStage,
  risk_notice: theme.riskNotice,
  candidate_stocks: theme.candidateStocks.map((stock) => ({
    company_name: stock.name,
    company_code: stock.code,
    purity_score: stock.score,
  })),
  validation_bucket: index === 0 ? "validated" : index === 1 ? "watch" : "pending",
  messages: theme.latestCatalysts.map((item, catalystIndex) => ({
    message_id: `MSG-${index + 1}-${catalystIndex + 1}`,
    title: item.title,
    summary: item.summary,
    event_time: item.eventTime,
    score: theme.lowPositionScore,
    validation_status: index === 0 ? "validated" : "watch",
  })),
}));

const workbenchMessages: MessageRow[] = workbenchThemes.flatMap((theme) =>
  theme.messages.map((message) => ({
    message: {
      message_id: message.message_id,
      title: message.title,
      summary: message.summary,
      event_time: message.event_time,
      source_name: "公开资讯",
      source_url: "",
      value_label: "观察",
      value_score: message.score ?? 0,
    },
    fermentation: {
      fermentation_verdict: theme.validation_bucket === "validated" ? "high" : "medium",
      fermentation_score: message.score ?? 0,
      why_it_may_ferment: [theme.low_position_reason],
      why_it_may_not_ferment: [theme.risk_notice],
      consensus_stage: theme.fermentation_phase,
    },
    impact: {
      primary_theme: theme.theme_name,
      impact_summary: theme.low_position_reason,
      impact_horizon: "短中期观察",
      impact_direction: "观察",
      impact_path: "公开事件 -> 主题聚合 -> 观察池",
      theme_confidence: 0.74,
      counter_themes: [],
    },
    companies: theme.candidate_stocks.map((stock) => ({
      company_name: String(stock.company_name ?? ""),
      company_code: String(stock.company_code ?? ""),
      role_label: "观察标的",
      relevance_score: Number(stock.purity_score ?? 0),
      purity_score: Number(stock.purity_score ?? 0),
      candidate_status: "watch",
      source_reason: "公开信息客观映射",
      source_reason_title: message.title,
      source_reason_url: "",
      llm_reason: "用于研究优先级排序。",
      crosscheck_status: "pending",
      reason_summary: "需继续核对证据。",
    })),
    validation: {
      validation_status: message.validation_status,
      validation_window: "T+3",
      observed_company_moves: [],
      observed_basket_move: {},
      observed_benchmark_move: {},
      excess_return: null,
      lagging_signal: false,
      calibration_action: "continue_watch",
      calibration_reason: "等待更多公开证据。",
      prediction_gap: "不做涨跌预测。",
      validation_summary: "仅校验研究链路闭环。",
    },
    score: {
      importance_score: message.score ?? 0,
      fermentation_score: message.score ?? 0,
      impact_quality_score: 70,
      company_discovery_score: 65,
      reason_quality_score: 80,
      market_validation_score: null,
      initial_actionability_score: message.score ?? 0,
      recalibrated_actionability_score: message.score ?? 0,
      final_verdict: "research_only",
      score_summary: "研究观察优先级。",
    },
  })),
);

export function createSeedSnapshot(date = SEED_DATE): DailySnapshot {
  return {
    date,
    storageTimezone: "Asia/Shanghai",
    dataMode: "seed",
    stats: {
      runCount: 1,
      sourceCount: 3,
      rawDocumentCount: 218,
      canonicalEventCount: seedEvents.length,
      themeCount: seedThemes.length,
      lowPositionCount: seedThemes.filter((item) => item.lowPositionScore !== null).length,
      fermentingThemeCount: seedThemes.filter((item) => item.fermentationScore >= 80).length,
    },
    commonRiskNotices: [
      "本内容仅为公开市场信息的客观整理，不构成投资建议。",
      "所有主题均需继续核对来源、证据片段和时间线。",
    ],
    sources: [
      { sourceId: "policy", sourceName: "公开政策", documentCount: 46 },
      { sourceId: "company", sourceName: "公司公告", documentCount: 72 },
      { sourceId: "media", sourceName: "权威财经媒体", documentCount: 100 },
    ],
    runs: [{ runId: "seed-ui-20260514", createdAt: `${date}T15:00:00+08:00`, rawDocumentCount: 218, eventCount: seedEvents.length, themeCount: seedThemes.length }],
    themes: seedThemes,
    events: seedEvents,
  };
}

export function createSeedWorkbench(date = SEED_DATE): LowPositionWorkbench {
  return {
    date,
    runId: "seed-low-position-20260514",
    createdAt: `${date}T15:10:00+08:00`,
    latestAvailableDate: SEED_DATE,
    dataMode: "seed",
    state: "success",
    messageCount: workbenchMessages.length,
    themeCount: workbenchThemes.length,
    stages: [
      { stage: "source", label: "公开来源接入", status: "pass" },
      { stage: "theme", label: "主题聚合", status: "pass" },
      { stage: "validation", label: "观察验证", status: "pass" },
    ],
    messages: workbenchMessages,
    themes: workbenchThemes,
    validatedThemes: workbenchThemes.filter((item) => item.validation_bucket === "validated"),
    watchThemes: workbenchThemes.filter((item) => item.validation_bucket !== "validated"),
    downgradedThemes: [],
  };
}
